### ISSUE TITLE
nb_matches

### ISSUE THREAD

**Issue by Huynh-Anh** [valette/FROG#5]
Hi,
I have managed to change the treshold via -d option i believe, but i notice that the number of matches exceeds the numbers of total keypoints after X threshold.
Is it normal ?

ty

**Comment by valette** [comment]
Hello,
yes this is possible since we are matching points from a set of N images. If each image contains k points, then the total number of matches can reach (N-1).k.k
I will provide much more documentation to the project today. Stay tuned!
