### ISSUE TITLE
Histograms files 

### ISSUE THREAD

**Issue by nasa92** [valette/FROG#6]
I managed to generate the files with your method. this generated me files for histograms. I traced them. for exemple 
![image](https://user-images.githubusercontent.com/47224618/99284119-435fc300-280c-11eb-9b02-c21862a85787.png)

Please can you explain more about these histograms ? how do we interpret these histogram files ? What I understood the histograms represent the orientation of the gradient in each image pixel. but I cannot see this concepts with your histogram. and what is the difference between linear histogram file and other histogram file.

Thanks for you response

**Comment by valette** [comment]
I have added more info to the Readme, is it ok?

**Comment by nasa92** [comment]
yes that's better, thanks for that.
Is there a way to visualise keypoints in 3d slicer or an image ?
