### ISSUE TITLE
VTK Files

### ISSUE THREAD

**Issue by Huynh-Anh** [valette/FROG#7]
Hi,
I am trying to visualise the keypoints on 3DSlicer. I notice that the keypoints list generated do not have an orientation matrix.
I see the coordinates, scale, a column of 0 or 1, and the descriptor.
How do I get the orientation matrix for each keypoint generated ?

Thank you again

**Comment by valette** [comment]
Hi,

Actually, there is no orientation matrix, as we use upright SURF. I have added more details on the keypoint format here: https://github.com/valette/vtkOpenSURF3D
